import type { Metadata } from 'next';
import { Cardo, Rubik } from 'next/font/google';
import '@/styles/globals.scss';

const cardo = Cardo({
  variable: '--font-cardo',
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['400', '700'],
});

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${cardo.variable} ${rubik.variable}`}>{children}</body>
    </html>
  );
}
